server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres?sslmode=require}
    username: ${DB_USERNAME:postgres.oqxpwrfqdaprwurixuoi}
    password: ${DB_PASSWORD:huwse6-Dejtar-hixjym}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 600000

  jpa:
    database-platform: ${JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}

app:
  jwtSecret: ${JWT_SECRET:DefaultSecretKeyWhichShouldBeLongEnoughForHS512AlgorithmSecurityPurpose}
  jwtExpirationMs: ${JWT_EXPIRATION_MS:86400000}